### ISSUE TITLE
Can't find the file or directory

### ISSUE THREAD

**Issue by lizhogn** [jindongwang/transferlearning#333]
https://github.com/jindongwang/transferlearning/blob/669a6008364b5e9815b0b31ce060d71ada8f5f1d/code/DeepDG/datautil/imgdata/imgdataload.py#L12

Is this a little bug that may cause the file can't be found error?

**Comment by jindongwang** [comment]
Could you please share more information, e.g., your terminal outputs?

**Comment by lizhogn** [comment]
Thanks for reply so fast. The output is as following: (can be simply solved by `root_dir+'\'+domain_name`, or use the os.path.join)
```bash
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    train_loaders, eval_loaders = get_img_dataloader(args)
  File "/home/zhognli/transferlearning/code/DeepDG/datautil/getdataloader.py", line 25, in get_img_dataloader
    tmpdatay = ImageDataset(args.dataset, args.task, args.data_dir,
  File "/home/zhognli/transferlearning/code/DeepDG/datautil/imgdata/imgdataload.py", line 12, in __init__
    self.imgs = ImageFolder(root_dir+domain_name).imgs
  File "/home/ustc/anaconda3/envs/dg/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/ustc/anaconda3/envs/dg/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/ustc/anaconda3/envs/dg/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/ustc/anaconda3/envs/dg/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhognli/transferlearning/data/office31amazon'
```
Is this the new feature for python3.8+? (path join directly by "+")

**Comment by lizhogn** [comment]
> 

Emm...I think I may ignore the last "/" in the arg `datadir`.

**Comment by jindongwang** [comment]
I see. Although this line is correct if you give it the correct directory, it's better be modified using `os.path.join`.

**Comment by lizhogn** [comment]
Yeah, thanks very much.
