### ISSUE TITLE
Failed to run KMM

### ISSUE THREAD

**Issue by lauraset** [jindongwang/transferlearning#346]
Hi, dear Wang, 
 I used a virtual environment (located in  "D:\code\CycleGAN\venv") 
and installed with python 3.6 and cvxopt (version 1.3.0) in windows 10. 
When I run the KMM code, it failed and showed the following message:
```
Traceback (most recent call last):
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\misc.py", line 1429, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 2065, in coneqp
    try: f = kktsolver(W)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 1981, in kktsolver
    return factor(W, P)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\misc.py", line 1444, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/code/tlbookcode/chap04_instance/kmm_fc.py", line 102, in <module>
    beta = kmm.fit(Xs, Xt)
  File "D:/code/tlbookcode/chap04_instance/kmm_fc.py", line 66, in fit
    sol = solvers.qp(K, -kappa, G, h)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 2067, in coneqp
    raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
ValueError: Rank(A) < p or Rank([P; A; G]) < n

Process finished with exit code 1

```
I am a novice at transfer learning. Do you know how to solve it? Thank you in advance.

**Comment by jindongwang** [comment]
Can't help you since no one runs these programs on Windows. Try Linux.
________________________________
发件人: YinxiaCao ***@***.***>
发送时间: Sunday, August 14, 2022 10:52:39 PM
收件人: jindongwang/transferlearning ***@***.***>
抄送: Subscribed ***@***.***>
主题: [jindongwang/transferlearning] Failed to run KMM (Issue #346)


Hi, dear Wang,
I used a virtual environment (located in "D:\code\CycleGAN\venv")
and installed with python 3.6 and cvxopt (version 1.3.0) in windows 10.
When I run the KMM code, it failed and showed the following message:

Traceback (most recent call last):
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\misc.py", line 1429, in factor
    lapack.potrf(F['S'])
ArithmeticError: 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 2065, in coneqp
    try: f = kktsolver(W)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 1981, in kktsolver
    return factor(W, P)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\misc.py", line 1444, in factor
    lapack.potrf(F['S'])
ArithmeticError: 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/code/tlbookcode/chap04_instance/kmm_fc.py", line 102, in <module>
    beta = kmm.fit(Xs, Xt)
  File "D:/code/tlbookcode/chap04_instance/kmm_fc.py", line 66, in fit
    sol = solvers.qp(K, -kappa, G, h)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "D:\code\CycleGAN\venv\lib\site-packages\cvxopt\coneprog.py", line 2067, in coneqp
    raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
ValueError: Rank(A) < p or Rank([P; A; G]) < n

Process finished with exit code 1



I am a novice at transfer learning. Do you know how to solve it? Thank you in advance.

―

**Comment by lauraset** [comment]
OK, I will try it. Thank you very much.
