### ISSUE TITLE
TCA.py: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by liguge** [jindongwang/transferlearning#355]
Xs_new, _ = self.fit(Xs, Xt)
        Xt2_new = self.fit_new(Xs, Xt, Xt2)
        clf = KNeighborsClassifier(n_neighbors=1)
        clf.fit(Xs_new, Ys.ravel())
        **y_pred = clf.predict(Xt2_new)**
        acc = sklearn.metrics.accuracy_score(Yt2, y_pred)

Traceback (most recent call last):

  File "E:\Program Files\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "E:\Program Files\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "E:\Program Files\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "E:\Program Files\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by liguge** [comment]
https://github.com/scikit-learn/scikit-learn/issues/24238

I have solved it!

**Comment by chentong456** [comment]
pip install threadpoolctl==3.1.0
