### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by majortsui** [jindongwang/transferlearning#379]
您好！我在用Adapter跑commonvoice数据集的时候出现了爆显存的问题：

2023-03-20 06:16:42,496 (train:126) WARNING: Training batch: 3756/22972
2023-03-20 06:16:43,054 (train:126) WARNING: Training batch: 3757/22972
Traceback (most recent call last):
  File "train.py", line 505, in <module>
    train(dataloaders, model, optimizer, save_path)
  File "train.py", line 280, in train
    train_stats = train_epoch(train_loader, model, optimizer, epoch)
  File "train.py", line 85, in train_epoch
    data_parallel(model, (fbank, seq_lens, tokens, language), range(args.ngpu))# .mean() # / self.accum_grad
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 231, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/miniconda/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/espnet/egs/commonvoice/asr1/Adapter/e2e_asr_adaptertransformer.py", line 665, in forward
    hs_pad, hs_mask = self.encoder(xs_pad, src_mask, language, use_sim_adapter=True)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/espnet/egs/commonvoice/asr1/Adapter/e2e_asr_adaptertransformer.py", line 254, in forward
    xs, masks, _, _, _ = self.encoders(xs, masks, language, None, use_sim_adapter)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/transformer/repeat.py", line 18, in forward
    args = m(*args)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/espnet/egs/commonvoice/asr1/Adapter/e2e_asr_adaptertransformer.py", line 155, in forward
    x, x_norm, mask = super().forward(x, mask, cache=cache)
  File "/opt/espnet/egs/commonvoice/asr1/Adapter/e2e_asr_adaptertransformer.py", line 106, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 114, in forward
    return self.forward_attention(v, scores, mask)
  File "/opt/espnet/espnet/nets/pytorch_backend/transformer/attention.py", line 84, in forward_attention
    self.attn = torch.softmax(scores, dim=-1).masked_fill(
RuntimeError: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 23.68 GiB total capacity; 19.89 GiB already allocated; 1.03 GiB free; 21.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

我是使用您的easyespnet中的镜像，把cuda升级到了11.6，pytorch升级到了1.12。我的显卡是NVIDIA GeForce RTX 3090 Ti * 2，一共是48G显存，在3700轮之前两张卡一直都分别只使用了5G显存左右，到了3757轮显存突然上去并且显示了cuda out of memory。CommonVoice数据集应该是50G左右，我运行的命令是“**python train.py --root_path /opt/espnet/egs/commonvoice/asr1 --dataset en --config config/adapter_example.yaml --adapter_train_languages en**”

想请教您是我运行的命令有问题吗？还是单纯因为显卡不够用？希望能得到您的讲解，万分感谢！

**Comment by majortsui** [comment]
我用了一个huggingface上的预训练模型：https://huggingface.co/eml914/streaming_transformer_asr_librispeech/tree/main/exp/asr_train_asr_streaming_fbank_pitch_en_bpe5000_sp

模型大小124MB。

**Comment by jindongwang** [comment]
应该是显存不够。这个当时用的是4卡V100，不知道你的显卡有多大。Speech没前途了，还是别搞了。。。

**Comment by majortsui** [comment]
> 

研究生想用您的adapter毕业呢(哭

**Comment by jindongwang** [comment]
那你可以多用点机器吧。Speech这领域不好搞了，影响力不大、还需要用很多卡，有点尴尬。OpenAI Whisper出来以后我觉得都不用做语音识别了。

**Comment by majortsui** [comment]
好的谢谢您，那我下去再试一试🙏
