### ISSUE TITLE
ValueError: Complex data not supported 运行CORAL.py时报错

### ISSUE THREAD

**Issue by blmoistawinde** [jindongwang/transferlearning#76]
运行CORAL.py时报错（对应代码中i=0,j=2时的情况）
```
Traceback (most recent call last):
  File "...\CORAL.py", line 59, in <module>
    acc, ypre = coral.fit_predict(Xs, Ys, Xt, Yt)
  File "...\CORAL.py", line 43, in fit_predict
    clf.fit(Xs_new, Ys.ravel())
  File "D:\Program files\Anaconda2\envs\py36\lib\site-packages\sklearn\neighbors\base.py", line 891, in fit
    X, y = check_X_y(X, y, "csr", multi_output=True)
  File "D:\Program files\Anaconda2\envs\py36\lib\site-packages\sklearn\utils\validation.py", line 756, in check_X_y
    estimator=estimator)
  File "D:\Program files\Anaconda2\envs\py36\lib\site-packages\sklearn\utils\validation.py", line 536, in check_array
    _ensure_no_complex_data(array)
  File "D:\Program files\Anaconda2\envs\py36\lib\site-packages\sklearn\utils\validation.py", line 359, in _ensure_no_complex_data
    "{}\n".format(array))
ValueError: Complex data not supported
[[-0.10956937+0.j -0.12825422+0.j -0.08698425+0.j ... -0.27869092+0.j
  -0.44214048+0.j -0.43824832+0.j]
 [-0.23875418+0.j  0.05269569+0.j -0.49858643+0.j ... -0.29306306+0.j
  -0.05399951+0.j -0.55347296+0.j]
 [ 1.11746535+0.j -0.48140165+0.j -0.42841533+0.j ... -0.12683256+0.j
  -0.69740877+0.j -0.28613614+0.j]
 ...
 [-0.48399652+0.j  0.26095685+0.j -0.13419323+0.j ...  0.07880897+0.j
  -0.83676863+0.j -0.1347447 +0.j]
 [-0.42397169+0.j  2.09933483+0.j  0.03859322+0.j ...  1.76172693+0.j
  -0.75844817+0.j  0.41763308+0.j]
 [-0.32876002+0.j  0.07707163+0.j -0.29121164+0.j ... -0.0470364 +0.j
  -0.21832906+0.j  0.32706655+0.j]]
```

原始数据中没有Complex类型，后来看了下，似乎是
```
A_coral = np.dot(scipy.linalg.fractional_matrix_power(cov_src, -0.5),
                         scipy.linalg.fractional_matrix_power(cov_tar, 0.5))
```
这一步以后数据有可能会变成Complex类型，所以我在下面一行加上了一个类型转换，
```
Xs_new = np.dot(Xs, A_coral).astype(float)
```
程序可以正常运行了。
不知道这样的转换对不对。如果对的话，或许可以修改一下代码预防这种小问题？谢谢王老师。

**Comment by jindongwang** [comment]
@blmoistawinde 这个问题没法避免，运算过程有可能出现复数。你的处理方式是对的，我们也都是这么处理的。可以在代码上加上这个步骤。感谢！
